"""remove priority

Revision ID: 17e60d83835f
Revises: cbd4be3a9b74
Create Date: 2026-04-23 05:55:17.906464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17e60d83835f'
down_revision = 'cbd4be3a9b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_history', 'priority')
    op.drop_index('ix_temporary_sites_priority', table_name='temporary_sites')
    op.drop_column('temporary_sites', 'priority')
    op.execute('DROP TYPE prioritylevel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_sites', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), autoincrement=False, nullable=True))
    op.create_index('ix_temporary_sites_priority', 'temporary_sites', ['priority'], unique=False)
    op.add_column('temporary_history', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

